/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TeamMember = {
  _type: "teamMember";
  name: string;
  role?: string;
  photo?: ImageWithAlt;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription?: string;
  email?: string;
  phone?: string;
  address?: string;
  mapsUrl?: string;
  instagram?: string;
  linkedin?: string;
  facebook?: string;
  contactFormRecipient: string;
};

export type Studio = {
  _id: string;
  _type: "studio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body?: RichText;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  seo?: Seo;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  category: CategoryReference;
  location?: string;
  year?: number;
  area?: number;
  description?: RichText;
  coverImage: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: string;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TeamMember
  | Seo
  | RichText
  | SanityImageAssetReference
  | ImageWithAlt
  | Settings
  | Studio
  | CategoryReference
  | Project
  | Category
  | Slug
  | ProjectReference
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && _id == "settings"][0] {    siteTitle,    siteDescription,    email,    phone,    address,    mapsUrl,    instagram,    linkedin,    facebook  }
export type SettingsQueryResult = {
  siteTitle: string;
  siteDescription: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  mapsUrl: string | null;
  instagram: string | null;
  linkedin: string | null;
  facebook: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: contactSettingsQuery
// Query: *[_type == "settings" && _id == "settings"][0] { siteTitle, contactFormRecipient }
export type ContactSettingsQueryResult = {
  siteTitle: string;
  contactFormRecipient: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: homeQuery
// Query: *[_type == "home" && _id == "home"][0] {    intro,    featuredProjects[]-> {      _id,      title,      "slug": slug.current,      coverImage {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }},      "category": category->title    },    seo { title, description, image {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }} }  }
export type HomeQueryResult = {
  intro: string | null;
  featuredProjects: Array<{
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      _key: null;
      alt: string;
      hotspot: {
        x: number;
        y: number;
      } | null;
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    };
    category: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _key: null;
      alt: string;
      hotspot: {
        x: number;
        y: number;
      } | null;
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project" && defined(slug.current)] | order(orderRank) {    _id,    title,    "slug": slug.current,    coverImage {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }},    "category": category->title,    location,    year  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  coverImage: {
    _key: null;
    alt: string;
    hotspot: {
      x: number;
      y: number;
    } | null;
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  };
  category: string;
  location: string | null;
  year: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    coverImage {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }},    "category": category->title,    location,    year,    area,    description,    gallery[] {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }},    seo { title, description, image {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }} }  }
export type ProjectQueryResult = {
  _id: string;
  title: string;
  slug: string;
  coverImage: {
    _key: null;
    alt: string;
    hotspot: {
      x: number;
      y: number;
    } | null;
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  };
  category: string;
  location: string | null;
  year: number | null;
  area: number | null;
  description: RichText | null;
  gallery: Array<{
    _key: string;
    alt: string;
    hotspot: {
      x: number;
      y: number;
    } | null;
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _key: null;
      alt: string;
      hotspot: {
        x: number;
        y: number;
      } | null;
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: projectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type ProjectSlugsQueryResult = Array<string>;

// Source: src/sanity/lib/queries.ts
// Variable: studioQuery
// Query: *[_type == "studio" && _id == "studio"][0] {    title,    body,    team[] { _key, name, role, photo {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }} },    seo { title, description, image {  _key,  alt,  hotspot { x, y },  asset->{ _id, metadata { dimensions { width, height } } }} }  }
export type StudioQueryResult = {
  title: string;
  body: RichText | null;
  team: Array<{
    _key: string;
    name: string;
    role: string | null;
    photo: {
      _key: null;
      alt: string;
      hotspot: {
        x: number;
        y: number;
      } | null;
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _key: null;
      alt: string;
      hotspot: {
        x: number;
        y: number;
      } | null;
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: sitemapQuery
// Query: *[_type == "project" && defined(slug.current)] {    "slug": slug.current,    _updatedAt  }
export type SitemapQueryResult = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "settings" && _id == "settings"][0] {\n    siteTitle,\n    siteDescription,\n    email,\n    phone,\n    address,\n    mapsUrl,\n    instagram,\n    linkedin,\n    facebook\n  }\n': SettingsQueryResult;
    '\n  *[_type == "settings" && _id == "settings"][0] { siteTitle, contactFormRecipient }\n': ContactSettingsQueryResult;
    '\n  *[_type == "home" && _id == "home"][0] {\n    intro,\n    featuredProjects[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n},\n      "category": category->title\n    },\n    seo { title, description, image {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n} }\n  }\n': HomeQueryResult;
    '\n  *[_type == "project" && defined(slug.current)] | order(orderRank) {\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n},\n    "category": category->title,\n    location,\n    year\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n},\n    "category": category->title,\n    location,\n    year,\n    area,\n    description,\n    gallery[] {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n},\n    seo { title, description, image {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n} }\n  }\n': ProjectQueryResult;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': ProjectSlugsQueryResult;
    '\n  *[_type == "studio" && _id == "studio"][0] {\n    title,\n    body,\n    team[] { _key, name, role, photo {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n} },\n    seo { title, description, image {\n  _key,\n  alt,\n  hotspot { x, y },\n  asset->{ _id, metadata { dimensions { width, height } } }\n} }\n  }\n': StudioQueryResult;
    '\n  *[_type == "project" && defined(slug.current)] {\n    "slug": slug.current,\n    _updatedAt\n  }\n': SitemapQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
